/* Generated by genrev.cmd from git. Do not edit. */
#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV         2588
#define SVN_REVSTR      "2588"
#define SVN_REVDATE     "2026-05-08"
#define SVN_REVSTAMP    20260508L
#define SVN_REVMODIFIED 1

#endif /* SVN_REV_H */
